"""
Monte Carlo Membership Inference Attack

This attack uses Monte Carlo sampling to estimate whether a candidate 
is a member of the training set. It samples from the model and compares
the reconstruction loss/distance of candidates against sampled data.
"""

from typing import Any, Optional, Tuple
import numpy as np
from scipy.spatial import distance as dist
from scipy.stats import percentileofscore
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from attack import attack


class MonteCarlo_attack(attack):
    name = "monte_carlo_attack"

    def __init__(
        self,
        n_samples: int = 1000,
        distance_metric: str = "euclidean",
        threshold: Optional[float] = None,
    ) -> None:
        """
        Initialize Monte Carlo Attack.

        Args:
            n_samples: Number of Monte Carlo samples to draw
            distance_metric: Distance metric to use ('euclidean', 'cosine', etc.)
            threshold: Decision threshold for membership (higher = member)
        """
        super().__init__(threshold=threshold)
        self.n_samples = n_samples
        self.distance_metric = distance_metric
        self.ref_distances = None
        self.mean_distance = None
        self.std_distance = None
        self.non_train_distances = None
        self.synthetic_distances = None
        self.combined_distances = None
        self.synthetic_mean_distance = None
        self.synthetic_std_distance = None

    def fit(self, synthetic_data: np.ndarray, non_train_data: np.ndarray):
        """Override fit to accept synthetic_data and non_train_data."""
        self._fit(synthetic_data=synthetic_data, non_train_data=non_train_data)
        self.is_fitted = True
        return

    def _fit(self, synthetic_data: np.ndarray, non_train_data: np.ndarray) -> None:
        """
        Fit the attack by computing minimum distances from non-training points to synthetic data
        and minimum distances between synthetic samples.

        Args:
            synthetic_data: Synthetic data generated by the model
            non_train_data: Non-training (non-member) data
        """
        if len(synthetic_data) < 2:
            raise ValueError("Synthetic data must contain at least 2 samples")
        if len(non_train_data) < 2:
            raise ValueError("Non-training data must contain at least 2 samples")

        # Ensure both datasets have the same size by taking the minimum length
        min_size = min(len(synthetic_data), len(non_train_data))
        synthetic_data = synthetic_data[:min_size]
        non_train_data = non_train_data[:min_size]

        # For each non-training point, compute minimum distance to any synthetic point
        non_train_distances = []
        for i in range(len(non_train_data)):
            distances = dist.cdist(
                [non_train_data[i]], synthetic_data, metric=self.distance_metric
            )[0]
            min_dist = np.min(distances)
            non_train_distances.append(min_dist)

        # For each synthetic point, compute minimum distance to any other synthetic point
        synthetic_distances = []
        for i in range(len(synthetic_data)):
            distances = dist.cdist(
                [synthetic_data[i]], synthetic_data, metric=self.distance_metric
            )[0]
            # Set distance to itself as infinity to ignore it
            distances[i] = np.inf
            min_dist = np.min(distances)
            synthetic_distances.append(min_dist)

        # Store both distributions
        self.non_train_distances = np.array(non_train_distances)
        self.synthetic_distances = np.array(synthetic_distances)
        
        # Combine both distances into a single sorted array
        self.combined_distances = np.sort(np.concatenate([self.non_train_distances, self.synthetic_distances]))
        
        # Sort distances in ascending order (low to high)
        self.non_train_distances = np.sort(self.non_train_distances)
        self.synthetic_distances = np.sort(self.synthetic_distances)
        
        # Sort distances from high to low (descending) for percentile calculation
        self.non_train_distances_sorted = self.non_train_distances[::-1]
        self.synthetic_distances_sorted = self.synthetic_distances[::-1]
        
        # Reference statistics from non-training data
        self.mean_distance = np.mean(self.non_train_distances)
        self.std_distance = np.std(self.non_train_distances)
        
        # Store synthetic distances statistics
        self.synthetic_mean_distance = np.mean(self.synthetic_distances)
        self.synthetic_std_distance = np.std(self.synthetic_distances) 

    def score(
        self,
        candidates: np.ndarray,
        reference_data: Optional[np.ndarray] = None,
        synthetic_data: Optional[np.ndarray] = None,
        **kwargs: Any,
    ) -> np.ndarray:
        """
        Compute membership scores using percentile-based ranking.
        
        For each candidate, computes the minimum distance to synthetic data,
        then returns the percentile of this distance in the sorted reference distribution.
        Lower distances result in higher percentile scores (closer to 1).
        Higher distances result in lower percentile scores (closer to 0).

        Args:
            candidates: Candidate samples to test (shape: [n_candidates, n_features])
            reference_data: Not used (kept for compatibility)
            synthetic_data: Synthetic data to compare against (required)
            **kwargs: Additional arguments

        Returns:
            Membership scores from 0 to 1 (higher = more likely member)
        """
        if synthetic_data is None:
            raise ValueError(
                "synthetic_data must be provided for Monte Carlo attack"
            )

        if len(candidates.shape) == 1:
            candidates = candidates.reshape(1, -1)

        if len(synthetic_data.shape) == 1:
            synthetic_data = synthetic_data.reshape(1, -1)

        scores = np.zeros(len(candidates))

        for i, candidate in enumerate(candidates):
            # Compute distances from candidate to all synthetic data
            distances = dist.cdist(
                [candidate], synthetic_data, metric=self.distance_metric
            )[0]
            
            # Get minimum distance to closest synthetic point
            min_dist = np.min(distances)
            
            # Calculate percentile of this distance in the sorted distribution
            # Using the non-training distances sorted in descending order
            # percentileofscore returns a value from 0 to 100
            percentile = percentileofscore(self.combined_distances, min_dist, kind='rank')
            
            # Normalize to 0-1 range
            score = 1- (percentile / 100.0)
            scores[i] = score

        return scores

    def predict(
        self,
        candidates: np.ndarray,
        reference_data: Optional[np.ndarray] = None,
        synthetic_data: Optional[np.ndarray] = None,
        threshold: Optional[float] = None,
        **kwargs: Any,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Predict membership of candidates using Monte Carlo attack.

        Args:
            candidates: Candidate samples to test
            reference_data: Not used (kept for compatibility)
            synthetic_data: Synthetic data to compare against
            threshold: Decision threshold (uses self.threshold if None)
            **kwargs: Additional arguments

        Returns:
            Tuple of (predictions, scores) where predictions are boolean
        """
        scores = self.score(candidates, synthetic_data=synthetic_data, **kwargs)
        thr = self.threshold if threshold is None else threshold

        if thr is None:
            raise ValueError(
                "No threshold available. Call fit(...) or pass threshold."
            )

        predictions = scores >= thr
        return predictions, scores
